### ISSUE TITLE
Train a model with nifti data

### ISSUE THREAD

**Issue by AmericaBG** [nish03/FunFuseAn#1]
Hi!
First of all, thank you very much for sharing your code, it's a great job, congratulations!

I would like to train my own model with my medical data that it's in .nii format. Is it possible?
Could you give me some advices about how to do it?

Thank you very much in advance :)

**Comment by nish03** [comment]
Hi!
  Thanks for reaching out. You could surely use a '.nii' format file to train a model. The '.nii' file is a volumetric format which means you will be able to extract a 3D numpy array from such a file. However, it depends on your use case whether you want to utilize the complete 3D array as an input to your model or you want to take 2D slices from such 3D data and then fed those as a 2D input to your model. In each of the mentioned scenarios, you definitely would need to perform the below steps to get the 3D numpy array extracted from your '.nii' file. 

```import os  
import numpy as np
from nibabel.testing import data_path
import nibabel as nib

filename = os.path.join(data_path, 'example.nii.gz')
img = nib.load(filename)
print(img.shape)
 ```

The  `img` should be a 3D array with `(x,y,z)` dimensions . If you want to extract a slice for `(x,y)`, then you need to fix `z`. Hope this helps!
